export const SET_KEY = 'SET_KEY'
export const SHOW_LOGIN = 'SHOW_LOGIN'
export const HIDE_LOGIN = 'HIDE_LOGIN'
export const IS_FIND_SWIPER = 'IS_FIND_SWIPER'
export const HIDE_FIND_SWIPER = 'HIDE_FIND_SWIPER'
export const SET_PLAY_LIST = 'SET_PLAY_LIST'